version: "3.8"

services:
  backend:
    build: ../Smart Metering System BackEnd
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "7211:7211"
      - "5191:5191"
    environment:
      - ConnectionStrings__Default=server=db;Port=3306;user=root;password=Inioluwa10%;database=SmartElectricMeteringSystem

  db:
    image: mysql:8.0
    networks:
      - app-network
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: SmartElectricMeteringSystem
      MYSQL_ROOT_PASSWORD: Inioluwa10%
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pInioluwa10%"]
      interval: 20s
      timeout: 10s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

networks:
  app-network:
