networks:
  app-network:

services:
  db:
    container_name: db
    image: mysql:8.0
    networks:
      - app-network
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: SEMS
      MYSQL_DATABASE: SmartElectricMeteringSystem
    volumes:
      - dbdata:/var/lib/mysql

  migrator:
    build: 
      context: ../Smart Metering System BackEnd
      dockerfile: Migrator.dockerfile
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - ConnectionStrings__Default=server=db;port=3306;user=root;password=SEMS;database=SmartElectricMeteringSystem

  backend:
    build: ../Smart Metering System BackEnd
    networks:
      - app-network
    depends_on:
      - migrator
    ports:
      - "7211:7211"
      - "5191:5191"
    environment:
      - ConnectionStrings__SmartElectricMeteringContext=server=db;port=3306;user=root;password=SEMS;database=SmartElectricMeteringSystem
      - ASPNETCORE_Kestrel__Certificates__Default__Password=SemsMeter
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/https.pfx
    volumes:
      - ./https.pfx:/https/https.pfx

volumes:
  dbdata:
